Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 130 # TODO: discuss and set this

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Style/Next:
  Enabled: false

# Disable length on tests
Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

